#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = 
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -I/home/stylix/local/include
CFLAGS_DEBUG = $(CFLAGS) -Wall -g -fopenmp `pkg-config --cflags opencv`
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L/home/stylix/local/lib
LIB_DEBUG = $(LIB)../alphautils/libalphautils.a -lopencv_world -lopencv_stitching -lopencv_videostab -lopencv_gpu -lopencv_legacy -lopencv_ts -lopencv_nonfree -lopencv_contrib -lopencv_calib3d -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_highgui -lopencv_flann -lopencv_imgproc -lopencv_ml -lopencv_core
LDFLAGS_DEBUG = $(LDFLAGS) `pkg-config --libs opencv` -lgomp -lrt -lpthread -ldl
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = ./libins.a

INC_RELEASE = $(INC) -I/home/stylix/local/include
CFLAGS_RELEASE = $(CFLAGS) -O3 -Wall -fopenmp `pkg-config --cflags opencv`
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L/home/stylix/local/lib
LIB_RELEASE = $(LIB)../alphautils/libalphautils.a -lopencv_world -lopencv_stitching -lopencv_videostab -lopencv_gpu -lopencv_legacy -lopencv_ts -lopencv_nonfree -lopencv_contrib -lopencv_calib3d -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_highgui -lopencv_flann -lopencv_imgproc -lopencv_ml -lopencv_core
LDFLAGS_RELEASE = $(LDFLAGS) -s `pkg-config --libs opencv` -lgomp -lrt -lpthread -ldl
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = ./libins.a

OBJ_DEBUG = $(OBJDIR_DEBUG)/dataset_info.o $(OBJDIR_DEBUG)/gvp.o $(OBJDIR_DEBUG)/homography.o $(OBJDIR_DEBUG)/ins_param.o $(OBJDIR_DEBUG)/invert_index.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/dataset_info.o $(OBJDIR_RELEASE)/gvp.o $(OBJDIR_RELEASE)/homography.o $(OBJDIR_RELEASE)/ins_param.o $(OBJDIR_RELEASE)/invert_index.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d . || mkdir -p .
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(AR) rcs $(OUT_DEBUG) $(OBJ_DEBUG)

$(OBJDIR_DEBUG)/dataset_info.o: dataset_info.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c dataset_info.cpp -o $(OBJDIR_DEBUG)/dataset_info.o

$(OBJDIR_DEBUG)/gvp.o: gvp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c gvp.cpp -o $(OBJDIR_DEBUG)/gvp.o

$(OBJDIR_DEBUG)/homography.o: homography.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c homography.cpp -o $(OBJDIR_DEBUG)/homography.o

$(OBJDIR_DEBUG)/ins_param.o: ins_param.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ins_param.cpp -o $(OBJDIR_DEBUG)/ins_param.o

$(OBJDIR_DEBUG)/invert_index.o: invert_index.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c invert_index.cpp -o $(OBJDIR_DEBUG)/invert_index.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf .
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d . || mkdir -p .
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/dataset_info.o: dataset_info.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c dataset_info.cpp -o $(OBJDIR_RELEASE)/dataset_info.o

$(OBJDIR_RELEASE)/gvp.o: gvp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c gvp.cpp -o $(OBJDIR_RELEASE)/gvp.o

$(OBJDIR_RELEASE)/homography.o: homography.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c homography.cpp -o $(OBJDIR_RELEASE)/homography.o

$(OBJDIR_RELEASE)/ins_param.o: ins_param.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ins_param.cpp -o $(OBJDIR_RELEASE)/ins_param.o

$(OBJDIR_RELEASE)/invert_index.o: invert_index.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c invert_index.cpp -o $(OBJDIR_RELEASE)/invert_index.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf .
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

